/// Tauri build script.
///
/// Two responsibilities:
/// 1. Wire `.env` (Supabase URL + anon key) into compile-time `env!()` so
///    `auth.rs` / `sync.rs` don't need a runtime config file.
/// 2. Register every IPC command with Tauri's ACL via
///    `AppManifest::commands(...)` so per-window capability files actually
///    gate them. Without this opt-in, custom app commands are implicitly
///    callable from any window with `core:default` — defeating the point of
///    splitting `main.json` / `settings.json` / `system-monitor.json` /
///    `onboarding.json`.
///
/// `commands(&[...])` causes tauri-build to autogenerate `allow-<cmd>` and
/// `deny-<cmd>` permissions under `permissions/autogenerated/`. Capability
/// files reference these as plain `allow-<cmd>` (no plugin prefix — the app
/// itself owns these permissions).
fn main() {
    // Load .env from project root (one level up from src-tauri/).
    // Silently ignored if .env doesn't exist (CI uses real env vars).
    let _ = dotenvy::from_path("../.env");

    // Re-run build.rs whenever .env changes so env!() macros pick up edits.
    println!("cargo:rerun-if-changed=../.env");
    println!("cargo:rerun-if-env-changed=SUPABASE_URL");
    println!("cargo:rerun-if-env-changed=SUPABASE_ANON_KEY");

    // Pass Supabase config as compile-time env vars.
    // Values come from .env (gitignored) or CI secrets.
    // If not set, defaults to empty strings — auth features will be disabled at runtime.
    println!(
        "cargo:rustc-env=SUPABASE_URL={}",
        std::env::var("SUPABASE_URL").unwrap_or_default()
    );
    println!(
        "cargo:rustc-env=SUPABASE_ANON_KEY={}",
        std::env::var("SUPABASE_ANON_KEY").unwrap_or_default()
    );

    // ---------------------------------------------------------------------
    // ACL: per-window command gating
    // ---------------------------------------------------------------------
    //
    // Every #[tauri::command] registered in `lib.rs` `generate_handler!`
    // must appear here, otherwise tauri-build will fail capability validation
    // when a window's capability file references a permission for an
    // unregistered command.
    //
    // KEEP THIS LIST IN SYNC WITH `src-tauri/src/lib.rs:invoke_handler`.
    // The order mirrors the handler block to make audits straightforward.
    const COMMANDS: &[&str] = &[
        // Window commands
        "show_window",
        "hide_window",
        "toggle_window",
        "center_window",
        "position_on_target_monitor",
        "update_show_on_screen",
        // App commands
        "scan_applications",
        "search_applications",
        "search_applications_frecency",
        "launch_application",
        "get_app_icon",
        // Launcher commands (with history tracking)
        "launch_app",
        "get_recent_apps",
        "get_frequent_apps",
        "get_pinned_apps",
        "pin_app",
        "unpin_app",
        "add_app_tag",
        "remove_app_tag",
        "get_apps_by_tag",
        "get_all_tags",
        "get_app_history",
        "clear_launch_history",
        "remove_from_history",
        "get_history_count",
        "get_frecency_suggestions",
        "record_search_selection",
        "open_path",
        "open_file_with_dialog",
        // Batch search command
        "search_all",
        // File indexing commands
        "start_indexing",
        "get_index_status",
        "search_files",
        "search_files_advanced",
        "search_files_with_highlighting",
        "get_indexed_file_count",
        "get_recent_files",
        "get_default_index_folders",
        "track_file_access",
        "clear_file_history",
        "get_file_categories",
        "get_index_stats",
        // Persistent index commands
        "invalidate_index",
        "get_db_index_stats",
        "start_file_watcher",
        "stop_file_watcher",
        // Settings commands
        "load_settings",
        "save_settings",
        "update_general_settings",
        "update_appearance_settings",
        "update_hotkey_settings",
        "update_indexing_settings",
        "update_plugin_settings",
        "update_shortcuts_settings",
        "update_shell_settings",
        "get_theme",
        "set_theme",
        "get_app_shortcuts",
        "save_app_shortcut",
        "delete_app_shortcut",
        "sync_app_shortcuts",
        "export_settings",
        "import_settings",
        // Hotkey commands
        "set_global_hotkey",
        "get_current_hotkey",
        // Autostart commands
        "enable_autostart",
        "disable_autostart",
        "is_autostart_enabled",
        // Window positioning commands
        "set_window_position",
        "get_window_position",
        // Plugin system commands
        "list_plugins",
        "get_all_plugins_info",
        "get_plugin_count",
        "get_enabled_plugin_count",
        "is_plugin_registered",
        "get_plugin_capabilities",
        "list_external_plugins",
        "get_plugins_directory",
        "validate_external_plugin",
        "load_plugin_from_file",
        "load_plugins_from_directory",
        "get_builtin_plugin_metadata",
        // Steam Scanner plugin commands
        "is_steam_installed",
        "get_steam_games",
        "launch_steam_game",
        "rescan_steam_library",
        "get_steam_installation_path",
        // System Monitor plugin commands
        "get_cpu_usage",
        "get_memory_usage",
        "get_disk_usage",
        "get_system_metrics",
        "get_system_metrics_v2",
        "kill_process_by_pid",
        "open_task_manager",
        // Game Scanner plugin commands
        "get_all_games",
        "search_games",
        "get_games_by_platform",
        "launch_game",
        "get_game_platforms",
        "rescan_all_games",
        "get_game_count",
        // Clipboard Manager plugin commands
        "get_clipboard_history",
        "search_clipboard_history",
        "check_clipboard",
        "toggle_clipboard_pin",
        "delete_clipboard_item",
        "clear_clipboard_history",
        "copy_to_clipboard",
        "start_clipboard_monitoring",
        "stop_clipboard_monitoring",
        "is_clipboard_monitoring",
        // Extension store commands
        "fetch_extension_registry",
        "get_installed_extensions",
        "install_extension",
        "uninstall_extension",
        "toggle_extension",
        "update_extension_permissions",
        "check_extension_updates",
        "update_extension",
        "get_extension_details",
        "read_extension_source",
        "get_enabled_extensions_sources",
        "get_extension_tamper_alert",
        "acknowledge_extension_tamper_alert",
        "fetch_extension_downloads",
        "increment_extension_download",
        // Extension storage API (per-extension key/value, gated by permission)
        "ext_storage_get",
        "ext_storage_set",
        "ext_storage_remove",
        "ext_storage_clear",
        // Extension preferences API
        "get_extension_preference",
        "set_extension_preference",
        "get_extension_secret",
        "set_extension_secret",
        "delete_extension_secret",
        // Extension OAuth API
        "ext_oauth_start",
        "ext_oauth_get_token",
        "ext_oauth_revoke_token",
        // Extension System API
        "ext_get_applications",
        "ext_show_in_folder",
        "ext_move_to_trash",
        // Dev extensions commands
        "scaffold_extension",
        "get_dev_extensions",
        "link_dev_extension",
        "unlink_dev_extension",
        "toggle_dev_extension",
        "get_dev_extensions_path",
        "refresh_dev_extension",
        "get_dev_reload_signal",
        // Credentials commands (load_credential intentionally omitted —
        // bare tokens must never cross the renderer boundary; M2)
        "save_credential",
        "has_credential",
        "delete_credential",
        "get_credential_info",
        "test_credential",
        "extension_authenticated_fetch",
        // Auth commands (Supabase)
        "auth_login",
        "auth_get_session",
        "auth_get_profile",
        "auth_refresh_token",
        "auth_logout",
        // OAuth commands
        "get_github_oauth_url",
        "get_notion_oauth_url",
        "is_oauth_pending",
        "clear_oauth_pending",
        // Logging commands
        "get_log_file_path",
        // Preview panel commands
        "get_file_preview",
        // Quicklink commands
        "get_quicklinks",
        "save_quicklink",
        "delete_quicklink",
        "open_quicklink",
        // Sync commands (premium)
        "sync_push",
        "sync_pull",
        "get_sync_status",
        // Snippet commands
        "get_snippets",
        "create_snippet",
        "update_snippet",
        "delete_snippet",
        "expand_snippet",
        "import_snippets",
        "export_snippets",
        // Notes commands
        "get_notes",
        "get_note",
        "get_trash",
        "create_note",
        "update_note",
        "delete_note",
        "restore_note",
        "empty_trash",
        "search_notes",
        "export_notes",
        "import_notes",
        // Embeddings commands (local AI)
        "embeddings_is_ready",
        "embeddings_prepare",
        "embeddings_test",
        // Notes window
        "open_notes_window",
        // Shell command execution
        "execute_shell_command",
        "execute_shell_command_streaming",
        "cancel_shell_command",
        // Shell command history
        "record_shell_command",
        "get_shell_history",
        "get_shell_suggestions",
        "pin_shell_command",
        "clear_shell_history",
        "remove_shell_command",
        // Streaming search
        "search_streaming",
        // Window management commands
        "snap_window",
        // Extension AI / OAuth / System APIs (callable from main + extensions worker)
        "ext_ai_ask_stream",
        // Global AI key management
        "ai_set_global_key",
        "ai_delete_global_key",
        "ai_get_providers_status",
        "ai_verify_key",
        // Built-in AI Chat
        "ai_ask_builtin_stream",
        // AI Profile
        "ai_profile_get",
        "ai_profile_set",
        // AI Quick Actions
        "ai_quick_actions_get",
        "ai_quick_actions_save",
        "ai_quick_actions_apply_all",
        "ai_quick_actions_read_clipboard",
        // Custom Emojis (SDXL Emoji via Replicate)
        "custom_emojis_generate",
        "custom_emojis_list",
        "custom_emojis_delete",
        "custom_emojis_has_token",
        "custom_emojis_copy_image",
        "ai_pro_features_enabled",
    ];

    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
