// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomPosition } from "./CustomPosition";

/**
 * Appearance settings
 */
export type AppearanceSettings = { theme: string, transparency: number, windowPosition: string, customPosition?: CustomPosition, };
