// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Application shortcut
 */
export type AppShortcut = { id: string, name: string, category: string, icon?: string, path: string, alias?: string, hotkey?: string, enabled: boolean, };
