// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-core CPU snapshot.
 */
export type CpuCoreInfo = { name: string, usagePercent: number, frequencyMhz: number, };
