// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageKind } from "./StorageKind";

/**
 * Per-disk snapshot. `available_gb` is derived for convenience; consumers can
 * verify against `used_gb = total_gb - available_gb` (within f32 rounding).
 */
export type DiskInfo = { mountPoint: string, totalGb: number, usedGb: number, availableGb: number, fileSystem: string, kind: StorageKind, };
