// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FallbackKind } from "./FallbackKind";

/**
 * A single fallback command that takes over when the regular search returns
 * no results. Inspired by Raycast's "Fallback Commands": the typed query is
 * substituted into the `target` template and the action runs.
 */
export type FallbackCommand = { id: string, label: string, icon: string | null, kind: FallbackKind,
/**
 * URL/command template — supports `{query}` (URL-encoded) and
 * `{rawQuery}` (unencoded) placeholders.
 */
target: string, enabled: boolean,
/**
 * Display order in the fallback list (lower = higher in the result list).
 */
order: number, };
