// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileCategory } from "./FileCategory";

/**
 * Represents a file in the index
 */
export type FileInfo = { id: string, name: string, path: string, extension: string, size: number, modified: number, created?: number, accessed?: number, icon?: string, 
/**
 * File category for filtering and scoring. `#[serde(default)]` means it is
 * always present on the wire (defaults to `other`), so it is a required
 * field in the generated binding — not optional. References the generated
 * `FileCategory.ts` automatically.
 */
category: FileCategory, };
