// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File category for intelligent filtering and scoring
 */
export type FileCategory = "application" | "game" | "executable" | "folder" | "document" | "image" | "video" | "audio" | "archive" | "code" | "other";
