// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * General application settings
 *
 * NOTE (single-source-of-truth scope): these structs are exported via ts-rs so
 * the IPC wire shape is captured in `src/shared/types/generated/`. The
 * frontend's hand-written `src/features/settings/types/settings.types.ts` is
 * intentionally kept as the UI-facing type because it carries richer literal
 * unions (`Theme`, `WindowPosition`, `ShowOnScreen`, `language`, etc.) and a
 * frontend-only `integrations?` field that has no Rust counterpart. ts-rs can
 * only emit `string` for those `String` fields, so collapsing the UI type onto
 * the generated one would *lose* type safety. The generated bindings therefore
 * serve as a verifiable contract / reference for the wire format, not as the
 * UI type.
 */
export type GeneralSettings = { startWithWindows: boolean, maxResults: number, closeOnLaunch: boolean, hasSeenOnboarding: boolean, language: string, featurePreview: boolean, searchSensitivity: string, showOnScreen: string, autoCheckForUpdates: boolean, updateChannel: string, };
