// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Indexing settings
 */
export type IndexingSettings = { folders: Array<string>, excludedPaths: Array<string>, fileExtensions: Array<string>, indexOnStartup: boolean, deepSearch: boolean, staleThresholdSecs: number, };
