// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Indexing settings
 */
export type IndexingSettings = {
  folders: Array<string>;
  excludedPaths: Array<string>;
  fileExtensions: Array<string>;
  indexOnStartup: boolean;
  deepSearch: boolean;
  /**
   * Re-walk the index on launch when the persisted snapshot is older than
   * this many seconds (the no-admin offline catch-up — see D3 in
   * `REFONTE-PILIER-D-SEARCH.md`). `0` disables the catch-up entirely.
   */
  staleThresholdSecs: number;
};
