// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Process summary used for the top-CPU and top-memory lists.
 *
 * `cpu_usage_percent` is a single-core percentage (sysinfo convention matches
 * htop / Task Manager "Details" tab) — values can exceed 100% on multithreaded
 * processes.
 */
export type ProcessInfo = { pid: number, name: string, cpuUsagePercent: number, memoryBytes: number, };
