// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * System metrics information
 */
export type SystemMetrics = { cpuUsage: number, memoryUsage: number, diskUsage: number, memoryTotalGb: number, memoryUsedGb: number, diskTotalGb: number, diskUsedGb: number, };
