export type { ComponentInfo } from '../../../../shared/types/generated/ComponentInfo';
export type { CpuCoreInfo } from '../../../../shared/types/generated/CpuCoreInfo';
export type { DiskInfo } from '../../../../shared/types/generated/DiskInfo';
export type { NetworkInfo } from '../../../../shared/types/generated/NetworkInfo';
export type { NetworkInterfaceInfo } from '../../../../shared/types/generated/NetworkInterfaceInfo';
export type { ProcessInfo } from '../../../../shared/types/generated/ProcessInfo';
export type { StorageKind } from '../../../../shared/types/generated/StorageKind';
export type { SystemMetrics } from '../../../../shared/types/generated/SystemMetrics';
export type { SystemMetricsV2 } from '../../../../shared/types/generated/SystemMetricsV2';
